from apit.store.constants import MP4_MAPPING

ORDERED_TRACK_TAGS = [
    MP4_MAPPING.TITLE,
    MP4_MAPPING.SORT_ORDER_TITLE,
    MP4_MAPPING.ARTIST,
    MP4_MAPPING.SORT_ORDER_ARTIST,
    MP4_MAPPING.COMPOSER,
    MP4_MAPPING.SORT_ORDER_COMPOSER,
    MP4_MAPPING.TRACK_NUMBER,
    MP4_MAPPING.RATING,
    MP4_MAPPING.GAPLESS,
    MP4_MAPPING.BPM,
    MP4_MAPPING.MEDIA_TYPE,
]
ORDERED_ALBUM_TAGS = [
    MP4_MAPPING.ALBUM_NAME,
    MP4_MAPPING.SORT_ORDER_ALBUM,
    MP4_MAPPING.ALBUM_ARTIST,
    MP4_MAPPING.SORT_ORDER_ALBUM_ARTIST,
    MP4_MAPPING.DISC_NUMBER,
    MP4_MAPPING.COMPILATION,
    MP4_MAPPING.GENRE,
    MP4_MAPPING.RELEASE_DATE,
    MP4_MAPPING.COPYRIGHT,
]
ORDERED_ID_TAGS = [
    MP4_MAPPING.CONTENT_ID,
    MP4_MAPPING.PLAYLIST_ID,
    MP4_MAPPING.ARTIST_ID,
    MP4_MAPPING.GENRE_ID,
    MP4_MAPPING.COMPOSER_ID,
    MP4_MAPPING.ISRC_ID,
]
ORDERED_MISC_TAGS = [
    MP4_MAPPING.TOOL,
    MP4_MAPPING.GROUPING,
    MP4_MAPPING.COMMENT,
    MP4_MAPPING.ARTWORK,
    MP4_MAPPING.LYRICS,
]
ORDERED_USER_TAGS = [
    MP4_MAPPING.OWNER_NAME,
    MP4_MAPPING.USER_MAIL,
    MP4_MAPPING.PURCHASE_DATE,
    MP4_MAPPING.STOREFRONT_ID,
]
