from apit.store.constants import MP4_MAPPING

ORDERED_TRACK_TAGS = [
    MP4_MAPPING.TITLE.value,
    MP4_MAPPING.SORT_ORDER_TITLE.value,
    MP4_MAPPING.ARTIST.value,
    MP4_MAPPING.SORT_ORDER_ARTIST.value,
    MP4_MAPPING.COMPOSER.value,
    MP4_MAPPING.SORT_ORDER_COMPOSER.value,
    MP4_MAPPING.TRACK_NUMBER.value,
    MP4_MAPPING.RATING.value,
    MP4_MAPPING.GAPLESS.value,
    MP4_MAPPING.BPM.value,
    MP4_MAPPING.MEDIA_TYPE.value,
]
ORDERED_ALBUM_TAGS = [
    MP4_MAPPING.ALBUM_NAME.value,
    MP4_MAPPING.SORT_ORDER_ALBUM.value,
    MP4_MAPPING.ALBUM_ARTIST.value,
    MP4_MAPPING.SORT_ORDER_ALBUM_ARTIST.value,
    MP4_MAPPING.DISC_NUMBER.value,
    MP4_MAPPING.COMPILATION.value,
    MP4_MAPPING.GENRE.value,
    MP4_MAPPING.RELEASE_DATE.value,
    MP4_MAPPING.COPYRIGHT.value,
]
ORDERED_ID_TAGS = [
    MP4_MAPPING.CONTENT_ID.value,
    MP4_MAPPING.PLAYLIST_ID.value,
    MP4_MAPPING.ARTIST_ID.value,
    MP4_MAPPING.GENRE_ID.value,
    MP4_MAPPING.COMPOSER_ID.value,
    MP4_MAPPING.ISRC_ID.value,
]
ORDERED_MISC_TAGS = [
    MP4_MAPPING.TOOL.value,
    MP4_MAPPING.GROUPING.value,
    MP4_MAPPING.COMMENT.value,
    MP4_MAPPING.ARTWORK.value,
    MP4_MAPPING.LYRICS.value,
]
ORDERED_USER_TAGS = [
    MP4_MAPPING.OWNER_NAME.value,
    MP4_MAPPING.USER_MAIL.value,
    MP4_MAPPING.PURCHASE_DATE.value,
    MP4_MAPPING.STOREFRONT_ID.value,
]
